"""add policy_config table

Revision ID: 227c5459da7d
Revises: 
Create Date: 2026-04-18 19:03:24.118969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '227c5459da7d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auto_response_enabled', sa.Boolean(), nullable=True),
    sa.Column('kill_on_alert', sa.Boolean(), nullable=True),
    sa.Column('quarantine_on_warn', sa.Boolean(), nullable=True),
    sa.Column('min_final_score_incident', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policy_config')
    # ### end Alembic commands ###
